# Generated by Django 5.0.8 on 2025-08-12 05:53

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours de traitement'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('TIMEOUT', 'Expiré')], max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('response_code', models.CharField(blank=True, max_length=10)),
                ('response_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tentative de Paiement',
                'verbose_name_plural': 'Tentatives de Paiement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('BANK_TRANSFER', 'Virement bancaire'), ('ESCROW_BANK', 'Compte séquestre')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('supports_collection', models.BooleanField(default=True)),
                ('supports_disbursement', models.BooleanField(default=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=100, max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, default=1000000, max_digits=15)),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='payment_methods/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Méthode de Paiement',
                'verbose_name_plural': 'Méthodes de Paiement',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_id', models.CharField(max_length=100, unique=True)),
                ('source', models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('ESCROW_BANK', 'Banque Séquestre')], max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('raw_data', models.JSONField()),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('RECEIVED', 'Reçu'), ('PROCESSING', 'En cours de traitement'), ('PROCESSED', 'Traité'), ('FAILED', 'Échoué'), ('IGNORED', 'Ignoré')], default='RECEIVED', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('last_processing_attempt', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frozen_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('FROZEN', 'Gelé'), ('CLOSED', 'Fermé')], default='ACTIVE', max_length=20)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('bank_response', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_account', to='escrow.escrowtransaction')),
            ],
            options={
                'verbose_name': 'Compte Séquestre',
                'verbose_name_plural': 'Comptes Séquestres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=core.utils.generate_payment_reference, max_length=50, unique=True)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('payment_type', models.CharField(choices=[('COLLECTION', 'Collecte de fonds'), ('DISBURSEMENT', 'Décaissement'), ('REFUND', 'Remboursement'), ('FEE', 'Frais de service')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours de traitement'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('TIMEOUT', 'Expiré')], default='PENDING', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='escrow.escrowtransaction')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
