# Generated by Django 5.0.8 on 2025-08-14 03:09

from django.db import migrations, models


def generate_email_from_phone(apps, schema_editor):
    """Générer un email unique pour les utilisateurs existants basé sur leur numéro de téléphone"""
    CustomUser = apps.get_model('users', 'CustomUser')
    
    for user in CustomUser.objects.all():
        if not user.email:
            # Générer un email basé sur le numéro de téléphone
            phone = user.phone_number or 'unknown'
            user.email = f"user_{phone.replace('+', '').replace('-', '')}@kimiescrow.temp"
            user.save()


def reverse_generate_email(apps, schema_editor):
    """Supprimer les emails temporaires générés"""
    CustomUser = apps.get_model('users', 'CustomUser')
    
    for user in CustomUser.objects.filter(email__endswith='@kimiescrow.temp'):
        user.email = ''
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        # D'abord, rendre email nullable temporairement
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, blank=True),
        ),
        # Générer des emails pour les utilisateurs existants
        migrations.RunPython(generate_email_from_phone, reverse_generate_email),
        # Maintenant rendre email non-nullable et unique
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        # Modifier phone_number pour être optionnel
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
