# Generated by Django 5.0.8 on 2025-08-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_password_reset_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
