# Generated by Django 5.0.8 on 2025-08-12 05:53

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispute_id', models.CharField(default=core.utils.generate_dispute_id, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('DELIVERY_ISSUE', 'Problème de livraison'), ('QUALITY_ISSUE', 'Problème de qualité'), ('PAYMENT_ISSUE', 'Problème de paiement'), ('COMMUNICATION_ISSUE', 'Problème de communication'), ('FRAUD', 'Fraude'), ('OTHER', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('ASSIGNED', 'Assigné'), ('IN_REVIEW', "En cours d'examen"), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé'), ('ESCALATED', 'Escaladé')], default='OPEN', max_length=20)),
                ('verdict', models.CharField(blank=True, choices=[('BUYER_FAVOR', "En faveur de l'acheteur"), ('SELLER_FAVOR', 'En faveur du vendeur'), ('PARTIAL_REFUND', 'Remboursement partiel'), ('NO_FAULT', 'Aucune faute')], max_length=20, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('review_started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10)),
            ],
            options={
                'verbose_name': 'Litige',
                'verbose_name_plural': 'Litiges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='dispute_attachments/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Commentaire de Litige',
                'verbose_name_plural': 'Commentaires de Litige',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('PHOTO', 'Photo'), ('VIDEO', 'Vidéo'), ('AUDIO', 'Audio'), ('MESSAGE', 'Message/Conversation'), ('OTHER', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='dispute_evidence/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Preuve de Litige',
                'verbose_name_plural': 'Preuves de Litige',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('reasoning', models.TextField()),
                ('buyer_action', models.TextField(blank=True)),
                ('seller_action', models.TextField(blank=True)),
                ('buyer_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seller_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('complainant_satisfied', models.BooleanField(blank=True, null=True)),
                ('respondent_satisfied', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Résolution de Litige',
                'verbose_name_plural': 'Résolutions de Litige',
            },
        ),
    ]
