# Generated by Django 5.0.8 on 2025-08-12 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disputes', '0001_initial'),
        ('escrow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='arbitre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitrated_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filed_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_against', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='escrow.escrowtransaction'),
        ),
        migrations.AddField(
            model_name='disputecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputecomment',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='disputes.dispute'),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='disputes.dispute'),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_evidences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputeresolution',
            name='dispute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='disputes.dispute'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['dispute_id'], name='disputes_di_dispute_c05b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'priority'], name='disputes_di_status_3dbe35_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['arbitre', 'status'], name='disputes_di_arbitre_d880b6_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['complainant'], name='disputes_di_complai_4b63ce_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['respondent'], name='disputes_di_respond_9f7493_idx'),
        ),
    ]
