# Generated by Django 5.0.8 on 2025-08-12 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='escrow.escrowtransaction'),
        ),
        migrations.AddField(
            model_name='proof',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='escrow.milestone'),
        ),
        migrations.AddField(
            model_name='proof',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proof',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='escrow.escrowtransaction'),
        ),
        migrations.AddField(
            model_name='proof',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionmessage',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='escrow.escrowtransaction'),
        ),
        migrations.AddField(
            model_name='transactionrating',
            name='rated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionrating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionrating',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='escrow.escrowtransaction'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['transaction_id'], name='escrow_escr_transac_35b41f_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['buyer', 'status'], name='escrow_escr_buyer_i_83d156_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['seller', 'status'], name='escrow_escr_seller__134d35_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['status', 'created_at'], name='escrow_escr_status_2d85b0_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['auto_release_date'], name='escrow_escr_auto_re_9cba8d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='milestone',
            unique_together={('transaction', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='transactionrating',
            unique_together={('transaction', 'rater', 'rated_user')},
        ),
    ]
