# Generated by Django 5.0.8 on 2025-08-14 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceToFaceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_location', models.CharField(help_text='Adresse ou lieu de rencontre', max_length=255)),
                ('meeting_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meeting_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meeting_address', models.TextField(blank=True)),
                ('meeting_date', models.DateTimeField(help_text='Date et heure de la rencontre')),
                ('meeting_duration', models.PositiveIntegerField(default=60, help_text='Durée prévue en minutes')),
                ('auto_validation_hours', models.PositiveIntegerField(default=24, help_text='Heures avant auto-validation')),
                ('auto_validation_deadline', models.DateTimeField(blank=True, null=True)),
                ('meeting_status', models.CharField(choices=[('SCHEDULED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée'), ('DISPUTED', 'En litige')], default='SCHEDULED', max_length=20)),
                ('meeting_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Détails Face-à-Face',
                'verbose_name_plural': 'Détails Face-à-Face',
            },
        ),
        migrations.CreateModel(
            name='InternationalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_currency', models.CharField(choices=[('XAF', 'Franc CFA'), ('USD', 'Dollar US'), ('EUR', 'Euro'), ('GBP', 'Livre Sterling')], max_length=3)),
                ('seller_currency', models.CharField(choices=[('XAF', 'Franc CFA'), ('USD', 'Dollar US'), ('EUR', 'Euro'), ('GBP', 'Livre Sterling')], max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('exchange_rate_fixed', models.BooleanField(default=False, help_text='Taux fixe ou variable')),
                ('exchange_rate_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('bill_of_lading', models.CharField(blank=True, max_length=100)),
                ('carrier_name', models.CharField(blank=True, choices=[('DHL', 'DHL'), ('FEDEX', 'FedEx'), ('UPS', 'UPS'), ('OTHER', 'Autre')], max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('tracking_url', models.URLField(blank=True)),
                ('inspection_days', models.PositiveIntegerField(default=5, help_text="Jours d'inspection (3-7)")),
                ('inspection_deadline', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Détails International',
                'verbose_name_plural': 'Détails Internationaux',
            },
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='currency',
            field=models.CharField(choices=[('XAF', 'Franc CFA'), ('USD', 'Dollar US'), ('EUR', 'Euro'), ('GBP', 'Livre Sterling')], default='XAF', max_length=3),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('STANDARD', 'Transaction Standard'), ('FACE_TO_FACE', 'Transaction Face-à-Face'), ('MILESTONE', 'Transaction par Jalons'), ('INTERNATIONAL', 'Transaction Internationale')], default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='proof',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='proof',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='Précision GPS en mètres', null=True),
        ),
        migrations.AddField(
            model_name='proof',
            name='location_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proof',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='proof',
            name='proof_type',
            field=models.CharField(choices=[('DELIVERY_PHOTO', 'Photo de livraison'), ('RECEIPT', 'Reçu'), ('SIGNATURE', 'Signature'), ('TRACKING', 'Numéro de suivi'), ('INVOICE', 'Facture'), ('WARRANTY', 'Garantie'), ('FACE_TO_FACE_INITIAL', 'Preuve initiale face-à-face'), ('FACE_TO_FACE_FINAL', 'Preuve finale face-à-face'), ('MILESTONE_PROOF', 'Preuve de jalon'), ('INTERNATIONAL_DOC', 'Document international'), ('OTHER', 'Autre')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['transaction_type'], name='escrow_escr_transac_bba893_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['currency'], name='escrow_escr_currenc_417da3_idx'),
        ),
        migrations.AddIndex(
            model_name='proof',
            index=models.Index(fields=['transaction', 'proof_type'], name='escrow_proo_transac_ff594d_idx'),
        ),
        migrations.AddIndex(
            model_name='proof',
            index=models.Index(fields=['milestone', 'proof_type'], name='escrow_proo_milesto_755ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='proof',
            index=models.Index(fields=['latitude', 'longitude'], name='escrow_proo_latitud_c572e8_idx'),
        ),
        migrations.AddField(
            model_name='facetofacedetails',
            name='final_proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_to_face_final', to='escrow.proof'),
        ),
        migrations.AddField(
            model_name='facetofacedetails',
            name='initial_proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_to_face_initial', to='escrow.proof'),
        ),
        migrations.AddField(
            model_name='facetofacedetails',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_to_face_details', to='escrow.escrowtransaction'),
        ),
        migrations.AddField(
            model_name='internationaldetails',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='international_details', to='escrow.escrowtransaction'),
        ),
    ]
